baseurl: "https://www.evoultimate.co.za"

title      : evo Ultimate – Bond Origination and Home Loan Experts
email      : lizzy.mootane@evogroup.co.za
description: evo Ultimate is dedicated to getting you the best deal on your homeloan by providing you with comparative quotes from seven of the major banks.  Let us secure your bond finance like so many buyers who have chosen us to manage their homeloans.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-NNGQT6HL3Y

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/evo-ultimate.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

company: evo Ultimate

group: evo Group

url: https://www.evoultimate.co.za

address: No. 4, 34 Dr van der Merwe Street, Montana, 0182