baseurl: "https://www.evoultimate.co.za"

title      : evo Ultimate – Bond Origination and Home Loan Experts
email      : lizzy.propertyassociate@gmail.com
description: evo Ultimate is dedicated to getting you the best deal on your homeloan by providing you with comparative quotes from seven of the major banks.  Let us secure your bond finance like so many buyers who have chosen us to manage their homeloans.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: 

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/evo-ultimate.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]