baseurl: ""
title      : evo Ultimate – Bond Origination and Home Loan Experts
email      : lizzy.mootane@evogroup.co.za
description: Compare home loan quotes from up to seven major banks with evo Ultimate's Pretoria bond origination experts. Our service is free to home buyers.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-NNGQT6HL3Y

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo: /assets/img/logo/evo-ultimate-logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

company: evo Ultimate
group: evo Home Loans

url: https://www.evoultimate.co.za
lang: en-ZA
address: Honey Suckle Street, Magalieskruin, Montana, 0182

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-minifier

# SEO tag defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      author: "Eben Roux / Pieter Oosthuizen"
      image: "/social_evulti.jpg"
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Eben Roux / Pieter Oosthuizen"

# Minification
jekyll-minifier:
  remove_spaces_around_tags: true
  remove_comments: true
  collapse_whitespace: true
  remove_empty_attributes: true
  remove_optional_attribute_quotes: false
  remove_redundant_attributes: true

sass:
  style: compressed

compress_html:
  clippings: all
  ignore:
    envs: development
